Default: &defaults
  database: dwreader.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: dwreader_test.sqlite3
  <<: *defaults

Staging:
  database: dwreader_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: dwreader_production.sqlite3
  poolsize: 100
  <<: *defaults
